# Python code for Chapter 3: SEASONAL CATCHMENT AREAS USING AN ATTRIBUTE BASED FUZZY LATTICE DATA STRUCTURE for toy example. Please note that the data used in POI catchment areas is not publically available and cannot be uploaded in this repository. Data ethics clearance number NAS003/2023.
 

# Importing all the relevant packages

In [8]:
import pandas as pd
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt
import networkx as nx
import os
from functools import reduce
from sklearn.preprocessing import StandardScaler, OneHotEncoder
# Enable inline plotting
%matplotlib inline

# NB: The names in the structured nodes (1-9) are in the ordered format for V that the labelled states are first  i.e. grid_name={1,2,3,4,5,6,7,8,9}={v2,v7,v1,v3,v4,v5,v6,v8,v9}


# Import Datasets

In [9]:
#Import Grid_Neighbours_Labels. 
# Grid_Name and Grid_Name2 indicates the the structural nodes adjacent to each other. 
# Absorbant_State indicates if grid_name is absorbant(1) or not and same for Absorbant_State2 for grid_name2. 
# Label_Val indicates the label associated with Grid_Name where for the toy example, P1 and P1 indicates the two POIs and U3-U9 indicates unlabelled.
base_path = '//cenana01/testcode/pythonUserVenv/michelled/Virtual_Environment/PhD/Chapter 3/'
file_path = os.path.join(base_path, 'Grid_Neighbours_Labels.txt')

DF = pd.read_csv(file_path, sep='|')
print(DF.head())

   Grid_Name  Grid_Name2  Absorbant_State  Absorbant_State2 Label_val
0          1           1                1                 1        P1
1          3           1                0                 1        U3
2          4           1                0                 1        U4
3          6           1                0                 1        U6
4          2           2                1                 1        P2


In [10]:
# Gives the attributes per grid. Each additional attribute will be added in another column the code is dynically set-up that way to pick up all distinct levels in all attributes provided
#For toy example there is one attribute with two levels the level a2 is associated with structural nodes v1 and v7 and level a1 with v2,v3,v4,v5,v6,v8 and v9.
file_path1 = os.path.join(base_path, 'Grid_Attributes.txt')

Attributes = pd.read_csv(file_path1, sep='|')
print(Attributes.head())

   grid_name attribute1
0          1         A1
1          2         A2
2          3         A2
3          4         A1
4          5         A1


In [11]:
# Degrees File. Distinct on grid_name and give the total number of neighbouring structural nodes(total) and if it is an absorbent state
file_path2 = os.path.join(base_path, 'Grid_Degrees.txt')

# Read the file
DF2 = pd.read_csv(file_path2, sep='|')
print(DF2.head())

absorbant_States=sum(DF2.Absorbant_State)
nodes=len(DF2.index)

   grid_Name  Absorbant_State  Total
0          1                1      3
1          2                1      2
2          3                0      2
3          4                0      2
4          5                0      3


# Create Adjacency Matrix

In [12]:
#Using the information from DF create adjacency matrix 
df = pd.crosstab(DF.Grid_Name, DF.Grid_Name2)
idx = df.columns.union(df.index)
df = df.reindex(index = idx, columns=idx, fill_value=0)

#Create correct format in Links table (new adjacency matrix)
links = np.matrix(df).astype(np.float64)
identity_abs = np.identity(absorbant_States)
#Absorbent states should only indicate 1 to own state, nullify absorbent states and replace top left hand corner of matrix with identity matrix
links[0:absorbant_States]=0
#Replace the identity matrix in the top left hand corner of links matrix that all absorbent states can only move into themselves
links[0:absorbant_States,0:absorbant_States]=identity_abs

#Links is now the adjacency matrix but all absorbent states only has a probability of 1 to stay in the same state with the rest 0
print(links)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]]


# Import the attributes and create attribute matrix X with N the number of structural nodes, A the total number of attributes and T total number of unique levels over all attributes

In [13]:
# Step 1: Order by grid_name
Attributes_sorted = Attributes.sort_values(by='grid_name')

# Step 2: Drop grid_name
Attributes_dropped = Attributes_sorted.drop(columns=['grid_name'])

# Step 3: Stack remaining columns into attributes_raw
attributes_raw = np.column_stack([Attributes_dropped[col].values for col in Attributes_dropped.columns])

# Convert the attributes_raw matrix to a DataFrame
df_attributes = pd.DataFrame(attributes_raw)
df_attributes.columns = df_attributes.columns.astype(str)

# Count the number of attributes (M)
A = df_attributes.shape[1]
N = links.shape[1]

# Extract all unique values across all attributes
distinct_values = np.unique(attributes_raw)

# Count the number of distinct values in all attributes (ki)
T = len(distinct_values)

# Initialize OneHotEncoder
encoder = OneHotEncoder()

# Fit and transform the categorical variables
attributes_encoded = encoder.fit_transform(df_attributes).toarray()

# Extract feature names from the encoder
feature_names = encoder.get_feature_names_out(df_attributes.columns)

# Create a new DataFrame with one-hot encoded columns
df_encoded = pd.DataFrame(attributes_encoded, columns=feature_names)

# Attribute matrix X
X = df_encoded.values

X = X.astype(np.float64)

print(N)
print(A)
print(T)

print(X)

9
1
2
[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [14]:
#Structural weights, if all is 1 it it equal to the adjacency matrix
w0=links
# Create w with the weights of the attributes
w = np.full(A, 1)

#Shell for transition matrix
transition_matrix = np.zeros((N + T, N + T))

#Sum over the rows of structural weights w0
row_sums = w0.sum(axis=1)
row_sums=row_sums.reshape((N, 1))

#sum over the rows of the attribute weights
attributes_sums = X.T.sum(axis=1)
attributes_sums=attributes_sums.reshape((T, 1))

# Create shell for submatrices with zeros
Matrix_Ps = np.zeros((N, N))
Matrix_Psa_Structure = X
Matrix_Pas=np.zeros((T,N))
Matrix_Pas_Structure = X.T
Matrix_0 = np.zeros((T, T))


# Create a dictionary to map attribute values to their corresponding weights
weights_dict = {}
for i in range(A):
    col_values = np.unique(df_attributes.iloc[:, i])
    for val in col_values:
        weights_dict[val] = w[i]

# Create the row vector w with the corresponding weights
wj = np.array([weights_dict[val] for val in distinct_values])
sum_weights=np.sum(w)

#From equations the values for submatrices
Matrix_Ps=w0/(row_sums+sum_weights)

Matrix_A=wj/(row_sums+sum_weights)
Matrix_A = np.asarray(Matrix_A)
Matrix_A *= Matrix_Psa_Structure

Matrix_Psa_Structure = np.asarray(Matrix_Psa_Structure)

Matrix_Pas=(1/attributes_sums) * Matrix_Pas_Structure

transition_matrix=np.vstack((np.hstack((Matrix_Ps,Matrix_A)),np.hstack((Matrix_Pas,Matrix_0))))
transition_matrix = np.round(transition_matrix, 6)

#The Transition matrix shown in the article has the order v1,v2,v3,...,v9,va1,va2 to illustrate the probabilities in each row without confusing the reader and is also Pa before introducing absorbent states. 
#The structure in the code is different with the absorbant states begin first i.e row 1 and column 1 is node v2 and row 2 and column 2 is node V7 as this matrix was set up for the label propagation
print(transition_matrix)

[[0.5      0.       0.       0.       0.       0.       0.       0.
  0.       0.5      0.      ]
 [0.       0.5      0.       0.       0.       0.       0.       0.
  0.       0.       0.5     ]
 [0.333333 0.       0.       0.       0.333333 0.       0.       0.
  0.       0.       0.333333]
 [0.333333 0.       0.       0.       0.       0.       0.333333 0.
  0.       0.333333 0.      ]
 [0.       0.25     0.25     0.       0.       0.25     0.       0.
  0.       0.25     0.      ]
 [0.2      0.       0.       0.       0.2      0.       0.2      0.2
  0.       0.2      0.      ]
 [0.       0.       0.       0.25     0.       0.25     0.       0.
  0.25     0.25     0.      ]
 [0.       0.25     0.       0.       0.       0.25     0.       0.
  0.25     0.25     0.      ]
 [0.       0.       0.       0.       0.       0.       0.333333 0.333333
  0.       0.333333 0.      ]
 [0.142857 0.       0.       0.142857 0.142857 0.142857 0.142857 0.142857
  0.142857 0.       0.      ]
 [0.   

# Check if matrix is stochastic

In [15]:
def is_row_stochastic(matrix):
    # Check non-negativity
    if np.any(matrix < 0):
        return False
    # Check if each row sum is within the range [0.99, 1.01]
    row_sums = matrix.sum(axis=1)
    return np.all((row_sums >= 0.99) & (row_sums <= 1.01))

# Example usage:
print("Is row stochastic?", is_row_stochastic(transition_matrix))

Is row stochastic? True


In [16]:
# Partition the transition matrix into blocks as indicated on article
P_ll = transition_matrix[:absorbant_States, :absorbant_States]
P_ul = transition_matrix[absorbant_States:, :absorbant_States]
P_uu = transition_matrix[absorbant_States:, absorbant_States:]

print(P_ll)
print(P_ul)
print(P_uu)

[[0.5 0. ]
 [0.  0.5]]
[[0.333333 0.      ]
 [0.333333 0.      ]
 [0.       0.25    ]
 [0.2      0.      ]
 [0.       0.      ]
 [0.       0.25    ]
 [0.       0.      ]
 [0.142857 0.      ]
 [0.       0.5     ]]
[[0.       0.       0.333333 0.       0.       0.       0.       0.
  0.333333]
 [0.       0.       0.       0.       0.333333 0.       0.       0.333333
  0.      ]
 [0.25     0.       0.       0.25     0.       0.       0.       0.25
  0.      ]
 [0.       0.       0.2      0.       0.2      0.2      0.       0.2
  0.      ]
 [0.       0.25     0.       0.25     0.       0.       0.25     0.25
  0.      ]
 [0.       0.       0.       0.25     0.       0.       0.25     0.25
  0.      ]
 [0.       0.       0.       0.       0.333333 0.333333 0.       0.333333
  0.      ]
 [0.       0.142857 0.142857 0.142857 0.142857 0.142857 0.142857 0.
  0.      ]
 [0.5      0.       0.       0.       0.       0.       0.       0.
  0.      ]]


In [17]:
# Calculate the stationary distribution for the unlabeled nodes
P_inf = inv(np.eye(P_uu.shape[0]) - P_uu).dot(P_ul)

# Define the labels for the labeled nodes
Y_l = np.identity(absorbant_States)  # Labels for node 1 and node 2

# Calculate the labels for the unlabeled nodes
Y_u = P_inf.dot(Y_l)

# Combine the results for all nodes
Y_all = np.vstack([Y_l, Y_u])

# Print the final probability matrix
print("Final probability matrix:")
print(Y_all)

Final probability matrix:
[[1.         0.        ]
 [0.         1.        ]
 [0.59390069 0.40609736]
 [0.78833178 0.21166501]
 [0.4847535  0.51524461]
 [0.66813817 0.33185965]
 [0.68802257 0.31197424]
 [0.49093962 0.50905798]
 [0.61864516 0.38135084]
 [0.67697515 0.32302144]
 [0.29695034 0.70304868]]


In [18]:
# Example usage:
print("Is row stochastic?", is_row_stochastic(Y_all))

Is row stochastic? True


# Drivetimes: Please note for the toy example the same nodes with be indicated for drive-times 5, 10 and 15minutes but for real-world applications like the pharmacy sales more nodes will be included as the drive times extend

In [19]:
# Only take the first N rows as only the strctural nodes can be used for drivetimes
L=Y_all[:N]

In [20]:
# The Grid_Name column indicates the grid that is allocated in the drive time circle of Store_Grid. I.e. grid names 1 and 2 are the only grids with a POI and which have a drivetime circle associated with it.
file_path3 = os.path.join(base_path, 'Grids_to_Drivetimes_5min.txt')

# Read the file
DT5 = pd.read_csv(file_path3, sep='|')
print(DT5)

   grid_name  store_grid
0          1           1
1          4           1
2          6           1
3          7           1
4          2           2
5          5           2
6          6           2
7          8           2


In [21]:
# The Grid_Name column indicates the grid that is allocated in the drive time circle of Store_Grid. I.e. grid names 1 and 2 are the only grids with a POI and which have a drivetime circle associated with it.
file_path4 = os.path.join(base_path, 'Grids_to_Drivetimes_10min.txt')

# Read the file
DT10 = pd.read_csv(file_path4, sep='|')
print(DT10)

   grid_name  store_grid
0          1           1
1          4           1
2          6           1
3          7           1
4          2           2
5          5           2
6          6           2
7          8           2


In [22]:
# The Grid_Name column indicates the grid that is allocated in the drive time circle of Store_Grid. I.e. grid names 1 and 2 are the only grids with a POI and which have a drivetime circle associated with it.
file_path5 = os.path.join(base_path, 'Grids_to_Drivetimes_15min.txt')

# Read the file
DT15 = pd.read_csv(file_path5, sep='|')
print(DT15)

   grid_name  store_grid
0          1           1
1          4           1
2          6           1
3          7           1
4          2           2
5          5           2
6          6           2
7          8           2


In [23]:
#5 minute drive time mappings
#Create and indicator matrix with the columns the POIs and the rows indicating which nodes are in the drive-times of those POIs
n_cols, n_rows = absorbant_States+1, nodes+1
Dist5 = np.zeros((n_rows, n_cols), dtype=np.int32)

Dist5[0,:] = np.arange(n_cols)
Dist5[:,0] = np.arange(n_rows)

d_selection5 = pd.DataFrame(DT5, columns = ['grid_name','store_grid'])

for i in range(len(d_selection5)):
    Dist5[d_selection5.loc[i, "grid_name"],d_selection5.loc[i, "store_grid"]]=1

Dist5=pd.DataFrame(Dist5)
Dist5 = Dist5.iloc[1: , 1:]
Dist5=pd.DataFrame(Dist5)
print(Dist5)

myArray5 = np.where(Dist5==0, Dist5, L)
myArray5[0:absorbant_States,0:absorbant_States]=identity_abs
res5 = myArray5/myArray5.sum(axis=1)[:,None]
res5=pd.DataFrame(res5)
res5=res5.fillna(0)

   1  2
1  1  0
2  0  1
3  0  0
4  1  0
5  0  1
6  1  1
7  1  0
8  0  1
9  0  0


In [24]:
#10 minute drive time mappings
#Create and indicator matrix with the columns the POIs and the rows indicating which nodes are in the drive-times of those POIs
n_cols, n_rows = absorbant_States+1, nodes+1
Dist10 = np.zeros((n_rows, n_cols), dtype=np.int32)

Dist10[0,:] = np.arange(n_cols)
Dist10[:,0] = np.arange(n_rows)

d_selection10 = pd.DataFrame(DT10, columns = ['grid_name','store_grid'])

for i in range(len(d_selection10)):
    Dist10[d_selection10.loc[i, "grid_name"],d_selection10.loc[i, "store_grid"]]=1

Dist10=pd.DataFrame(Dist10)
Dist10 = Dist10.iloc[1: , 1:]
Dist10=pd.DataFrame(Dist10)
print(Dist10)

myArray10 = np.where(Dist10==0, Dist10, L)
myArray10[0:absorbant_States,0:absorbant_States]=identity_abs
res10 = myArray10/myArray10.sum(axis=1)[:,None]
res10=pd.DataFrame(res10)
res10=res10.fillna(0)

   1  2
1  1  0
2  0  1
3  0  0
4  1  0
5  0  1
6  1  1
7  1  0
8  0  1
9  0  0


In [25]:
#15 minute drive time mappings
#Create and indicator matrix with the columns the POIs and the rows indicating which nodes are in the drive-times of those POIs
n_cols, n_rows = absorbant_States+1, nodes+1
Dist15 = np.zeros((n_rows, n_cols), dtype=np.int32)

Dist15[0,:] = np.arange(n_cols)
Dist15[:,0] = np.arange(n_rows)

d_selection15 = pd.DataFrame(DT15, columns = ['grid_name','store_grid'])

for i in range(len(d_selection15)):
    Dist15[d_selection15.loc[i, "grid_name"],d_selection15.loc[i, "store_grid"]]=1

Dist15=pd.DataFrame(Dist15)
Dist15 = Dist15.iloc[1: , 1:]
Dist15=pd.DataFrame(Dist15)
print(Dist15)

myArray15 = np.where(Dist15==0, Dist15, L)
myArray15[0:absorbant_States,0:absorbant_States]=identity_abs
res15 = myArray10/myArray15.sum(axis=1)[:,None]
res15=pd.DataFrame(res15)
res15=res15.fillna(0)

   1  2
1  1  0
2  0  1
3  0  0
4  1  0
5  0  1
6  1  1
7  1  0
8  0  1
9  0  0


# Supply and demand to calculate supply-demand ratio and accessibility

In [26]:
# The Grid_Name column indicates the grid that is allocated in the drive time circle of Store_Grid. I.e. grid names 1 and 2 are the only grids with a POI and which have a drivetime circle associated with it.
#The Demand for each grid in the toy example is 1
file_path6 = os.path.join(base_path, 'Grid_Demand.txt')

# Read the file
Grid_Demand = pd.read_csv(file_path6, sep='|')

# Convert grid_name to numeric if it's stored as string
Grid_Demand['grid_name'] = Grid_Demand['grid_name'].astype(int)
# Now sort
Grid_Demand.sort_values('grid_name', inplace=True)
Grid_Demand.reset_index(drop=True, inplace=True)
print(Grid_Demand)

   grid_name  Total
0          1      1
1          2      1
2          3      1
3          4      1
4          5      1
5          6      1
6          7      1
7          8      1
8          9      1


In [27]:
# The Grid_Name column indicates the grid that is allocated in the drive time circle of Store_Grid. I.e. grid names 1 and 2 are the only grids with a POI and which have a drivetime circle associated with it.
# The supply for the toy example for P1 and P2 is 4 
file_path7 = os.path.join(base_path, 'Grid_Supply.txt')

# Read the file
Grid_Supply = pd.read_csv(file_path7, sep='|')
print(Grid_Supply)

   grid_name  total_sales
0          1            4
1          2            4


In [28]:
#Calculate the total demand per grid based on the drive time rings: Demand at 5 minute drive-times
Grid_Demand=pd.DataFrame(Grid_Demand)
Grid_T=Grid_Demand.Total
res5_T=res5.T

Grid_Demand_5min=np.multiply(res5_T,Grid_T)
Grid_Demand_5min=Grid_Demand_5min.T

Total_Grid_Demand_5min=round(Grid_Demand_5min.sum(axis='rows'),2)
Total_Grid_Demand_5min=pd.DataFrame(Total_Grid_Demand_5min)
Total_Grid_Demand_5min.rename(columns={0:'Total_Grid_5min'})
Total_Grid_Demand_5min.insert(0, 'grid_name', range(1, 1 + len(Total_Grid_Demand_5min)))
Total_Grid_Demand_5min.rename(columns={0:'Total_Grid_5min'})

grid_name  Total_Grid_5min
0          1             3.67
1          2             3.33

In [29]:
#Calculate the total demand per grid based on the drive time rings: Demand at 10 minute drive-times
Grid_Demand=pd.DataFrame(Grid_Demand)
Grid_T=Grid_Demand.Total
res10_T=res10.T

Grid_Demand_10min=np.multiply(res10_T,Grid_T)
Grid_Demand_10min=Grid_Demand_10min.T
Total_Grid_Demand_10min=round(Grid_Demand_10min.sum(axis='rows'),2)
Total_Grid_Demand_10min=pd.DataFrame(Total_Grid_Demand_10min)
Total_Grid_Demand_10min.rename(columns={0:'Total_Grid_10min'})
Total_Grid_Demand_10min.insert(0, 'grid_name', range(1, 1 + len(Total_Grid_Demand_10min)))
Total_Grid_Demand_10min.rename(columns={0:'Total_Grid_10min'})

grid_name  Total_Grid_10min
0          1              3.67
1          2              3.33

In [30]:
#Calculate the total demand per grid based on the drive time rings: Demand at 15 minute drive-times
Grid_Demand=pd.DataFrame(Grid_Demand)
Grid_T=Grid_Demand.Total
res15_T=res15.T

Grid_Demand_15min=np.multiply(res15_T,Grid_T)
Grid_Demand_15min=Grid_Demand_15min.T
Total_Grid_Demand_15min=round(Grid_Demand_15min.sum(axis='rows'),2)
Total_Grid_Demand_15min=pd.DataFrame(Total_Grid_Demand_15min)
Total_Grid_Demand_15min.rename(columns={0:'Total_Grid_15min'})
Total_Grid_Demand_15min.insert(0, 'grid_name', range(1, 1 + len(Total_Grid_Demand_15min)))
Total_Grid_Demand_15min.rename(columns={0:'Total_Grid_15min'})

grid_name  Total_Grid_15min
0          1              3.67
1          2              3.33

In [31]:
# merge all drive times together and supply
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['grid_name'],how='outer'), (Grid_Supply,Total_Grid_Demand_5min,Total_Grid_Demand_10min,Total_Grid_Demand_15min))        
df_merged=pd.DataFrame(df_merged)
df_merged.set_axis(['GRID_NAME', 'Total_Sales','Total_Demand_5min','Total_Demand_10min','Total_Demand_15min'], axis='columns', inplace=True)
print(df_merged)

   GRID_NAME  Total_Sales  Total_Demand_5min  Total_Demand_10min  \
0          1            4               3.67                3.67   
1          2            4               3.33                3.33   

   Total_Demand_15min  
0                3.67  
1                3.33  


In [32]:
#Add Supply-Demand Ratio for each drive-time. Since for the toy example all drivetimes are the same, the supply-demand ratio is also the same for 5,10 and 15min
df_merged['Total_Sales'].fillna(0, inplace=True)
df_merged['Total_Demand_5min'].fillna(0, inplace=True)

df_merged['Total_Sales'] = pd.to_numeric(df_merged['Total_Sales'], errors='coerce')
df_merged['Total_Demand_5min'] = pd.to_numeric(df_merged['Total_Demand_5min'], errors='coerce')

df_merged['AR_5min']=df_merged['Total_Sales']/df_merged['Total_Demand_5min']
df_merged['AR_10min']=df_merged['Total_Sales']/df_merged['Total_Demand_10min']
df_merged['AR_15min']=df_merged['Total_Sales']/df_merged['Total_Demand_15min']

df_merged=pd.DataFrame(df_merged)
df_merged.fillna(0, inplace=True)
df_merged.sort_values(['GRID_NAME'], inplace=True)
df_merged = df_merged.round(2)

print(df_merged)

#The supply-demand ration for P1 is 1.09 and the supply-demand ration for P2 is 1.2 

   GRID_NAME  Total_Sales  Total_Demand_5min  Total_Demand_10min  \
0          1            4               3.67                3.67   
1          2            4               3.33                3.33   

   Total_Demand_15min  AR_5min  AR_10min  AR_15min  
0                3.67     1.09      1.09      1.09  
1                3.33     1.20      1.20      1.20  


# Calculate the accessibility per grid

In [33]:
Accessibility_5min = np.matmul(Dist5,df_merged.AR_5min)
Accessibility_10min = np.matmul(Dist10,df_merged.AR_10min)
Accessibility_15min = np.matmul(Dist15,df_merged.AR_15min)

Accessibility = [Accessibility_5min,Accessibility_10min,Accessibility_15min]
Accessibility=pd.DataFrame(Accessibility)
Accessibility=Accessibility.T
Accessibility.set_axis(['Accessibility_5min', 'Accessibility_10min', 'Accessibility_15min'], axis='columns', inplace=True)   

# Round all values to 2 decimal places
Accessibility = Accessibility.round(2)

print("Updated Accessibility DataFrame:")
print(Accessibility)
#The accessibility for grid v5 which in the ordered set V={v2,v7,v1,v3,v4,v5,v6,v8,v9} is grid_name 6 is 2.29


Updated Accessibility DataFrame:
   Accessibility_5min  Accessibility_10min  Accessibility_15min
1                1.09                 1.09                 1.09
2                1.20                 1.20                 1.20
3                0.00                 0.00                 0.00
4                1.09                 1.09                 1.09
5                1.20                 1.20                 1.20
6                2.29                 2.29                 2.29
7                1.09                 1.09                 1.09
8                1.20                 1.20                 1.20
9                0.00                 0.00                 0.00
